### ISSUE TITLE
set_nodelay for TcpStream is deprecated

### ISSUE THREAD

**Issue by benaryorg** [kjpgit/mudpie#3]
The line

```rust
raw_stream.set_nodelay(true).unwrap();
```

will not work anymore as of rustc 1.4.0-nightly and [was moved to the net2 crate](https://doc.rust-lang.org/std/net/struct.TcpStream.html#method.set_nodelay).

mudpie's readme states that
> Mudpie is written in 100% safe Rust code (no unsafe blocks) and has no dependencies.

which would not be fulfilled anymore then.

I built a stable-compatible version on my [fork](https://github.com/benaryorg/mudpie) and would send a PR if you want (currently there is a fixme at the line using `set_nodelay`).

**Edit:** My fork keeps giving the error `Error when reading request: connection closed while reading request headers`.

**Comment by kjpgit** [comment]
Thanks for the heads up.  I have to say I'm losing faith in rust at this point.  

It's bad enough for network daemons that TCP_CORK isn't supported, but now even TCP_NODELAY is getting axed from stable?  I can't even ...  

The rest of the churn in the patch looks just as frustrating.   Still no stable and efficient ascii_lowercase function?   Still no documented "optimized" Vec::extend?   I give up.

Apple, please save us.

**Comment by benaryorg** [comment]
> Thanks for the heads up.

I think [nightli.es](http://nightli.es) could help keeping your things up-to-date.

> getting axed from stable

As far as I understood Rust tries to split such parts off into crates so Rust stays a language with a **really** minimal runtime and *opt-in* extra features.

**Comment by benaryorg** [comment]
[`TcpStream::set_nodelay`](http://doc.rust-lang.org/nightly/std/net/struct.TcpStream.html#method.set_nodelay) seems to be stable now, as of [Rust's README.md](https://github.com/rust-lang/rust/blob/master/RELEASES.md).
